Completed the works and middle section
shaaibu7/Portfolio-project pull request #2
Opened 2022-12-02 12:17 UTC by shaaibu7

Completed the building works section and about myself for the mobile version of the portfolio website.

2022-12-02 13:28 UTC, Felix45 requested changes
Hi @shaaibu7 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] Good pull request title :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 
- [ ] Correct GitHub flow :white_check_mark: 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 13:28 UTC, Felix45 commented on index.html
> +         <main class="middle">
- [ Required ] Please consider laying out the contents of the main container of your web page using `grid` since this is part of the project requirement. Please see the screenshot below for more instructions on this.
![Screenshot from 2022-12-02 15-55-09](https://user-images.githubusercontent.com/16392046/205297918-7a05fe18-4d6e-4168-bf57-6d0b35abfba9.png)

2022-12-02 13:28 UTC, Felix45 commented on index.html
> +                    </ul>
-[ Required ] Please consider adding the links to all your social media pages in the `href` attribute, these links might be clicked by recruiters who want to reach out to you so it's important that you provide active links to your social media pages.

2022-12-02 13:28 UTC, Felix45 commented on style.css
> +  background-color: #e5e5e5;
- [ Required ] Please consider applying the right background color to the individual sections of your portfolio, not all of the `I'm Suleiman Welcome To My Portfolio Website` part of your design should not have dark grey background color as currently implemented. Please see the screenshot below and rectify this.

## Figma template Vs Your implmentation
<img src="https://user-images.githubusercontent.com/16392046/205301131-a8f146ab-f449-4b3c-836a-bb4ae0d6b707.png" width="300px" />     <img src="https://user-images.githubusercontent.com/16392046/205301573-b49bc9c7-5b0a-4ead-bdde-dabc1a3d7e22.png" width="300px" />

2022-12-03 01:03 UTC, mgmediaweb approved these changes
Hi @shaaibu7 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved5](https://user-images.githubusercontent.com/41912912/205414849-af7f12bb-08cc-4aa0-80d0-260f2a3eec30.gif)

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 01:13 UTC, merged